server:
  port: 0

spring:
  kafka:
    bootstrap-servers: ${HOST}:9092

  datasource:
    url: jdbc:postgresql://postgres:5432/authorization_db?currentSchema=schema_authorization
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    user: ${SPRING_LIQUIBASE_USER}
    password: ${SPRING_LIQUIBASE_PASSWORD}
    drop-first: false

  data:
    redis:
      host: ${HOST}

#  cloud:
#    config:
#      import-check:
#        enabled: false
#      discovery:
#        enabled: true
#        service-id: config-service
#      fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST}:8761/eureka/
    enabled: true
  instance:
    preferIpAddress: true  # Регистрировать IP-адрес контейнера в Eureka