spring:
  application:
    name: AUTH-SERVICE

  profiles:
    active: dev
#    active: test
#    active: testEureka

  datasource:
    hikari:
     schema: schema_authorization
     connection-init-sql: create schema if not exists schema_authorization
     connection-timeout: 10000

  liquibase:
    change_log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  data:
    redis:
      port: 6379

  main:
    allow-circular-references: true
  jpa:
    generate-ddl: false
    open-in-view: true

app:
  kafka:
    topicProducer: "registration-topic"
    topicListener: "created-account-topic"
    kafkaMessageGroupId: "kafka-account-group-id"
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 30m
  mail:
    user: tdsuser45@mail.ru
    password: n3c421ZcGyinuqdKJyie

#logging:
#  level:
#    root: debug