server:
  port: 0

spring:
  kafka:
    bootstrap-servers: ${HOST}:9092

  datasource:
    url: jdbc:postgresql://postgres:5432/authorization_db?currentSchema=schema_authorization
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    drop-first: false

  data:
    redis:
      host: ${HOST}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST}:8761/eureka/
    enabled: true
  instance:
    preferIpAddress: true
