server:
  port: 0
  servlet:
    session:
      cookie:
        name: JSESSIONID
        secure: true          # только HTTPS (для тестов можно временно false)
        http-only: true
        same-site: none       # важно для cross-site запросов
        domain: bakery45.ru   # общий домен для фронта и API

spring:
  kafka:
    bootstrap-servers: ${HOST}:9094

  datasource:
    url: jdbc:postgresql://postgres:5432/authorization_db?currentSchema=schema_authorization
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    drop-first: false

  data:
    redis:
      port: 6379
      host: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST}:8761/eureka/
    enabled: true
  instance:
    preferIpAddress: true
