spring:
  application:
    name: auth-service

  profiles:
    active: dev
#    active: test
#    active: testEureka

  datasource:
    hikari:
     schema: schema_authorization
     connection-init-sql: create schema if not exists schema_authorization
     connection-timeout: 10000

  liquibase:
    change_log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

  data:
    redis:
      port: 6379

  main:
    allow-circular-references: true
  jpa:
    generate-ddl: false
    open-in-view: true

app:
  kafka:
    topicProducerRegistration: "registration-topic"
    topicProducerUserIsOnline: "user-is-online-topic"
    topicProducerChangedEmail: "changed-email-topic"
    topicListenerCreatedAccount: "created-account-topic"

    kafkaMessageGroupId: "kafka-account-group-id"
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 15m
    refreshTokenExpiration: 24h
  mail:
    user: ${MAIL_USER}
    password: ${MAIL_PASSWORD}

#logging:
#  level:
#    root: debug