server:
  port: 0
  servlet:
    session:
      cookie:
        domain: ${DOMAIN}
        same-site: none
        secure: true

spring:
  kafka:
    bootstrap-servers: ${HOST}:9094

  datasource:
    url: jdbc:postgresql://postgres:5432/authorization_db?currentSchema=schema_authorization
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    drop-first: false

  data:
    redis:
      host: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST}:8761/eureka/
    enabled: true
  instance:
    preferIpAddress: true
